[project]
name = "multiagent-rag-pdf-review"
version = "0.1.0"
description = "Pipeline multiagente con RAG para detectar errores en documentos académicos"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "streamlit",
    "pymupdf",
    "pdfplumber",
    "transformers",
    "torch",
    "chromadb",
    "sentence-transformers",
    "groq",
    "language-tool-python",
    "uvicorn",
    "python-dotenv",
    "python-multipart",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"